title: lena's notebook
theme: jekyll-theme-minimal

markdown: kramdown
kramdown:
  input: GFM

# Use our own layout/CSS instead of the theme's default look
plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: false